steps:
  - name: node:12
    entrypoint: npm
    args: ['install']

  - name: node:13
    entrypoint: npm
    args: [ 'run', 'config' ]
    env:
      - 'GRAPHQL_TOKEN=${_GRAPHQL_TOKEN}'
      - 'BASE_URL=${_BASE_URL}'
      - 'PRODUCTION=${_PRODUCTION}'

  - name: node:12
    entrypoint: npm
    args: ['run', 'build:ssr']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy','$_APP_CONFIG','--project', '$PROJECT_ID']

timeout: '1600s'
